//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hNext.ResourceLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hNext.ResourceLibrary.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дім.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відміна.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити зміни та вийти.
        /// </summary>
        public static string CancelAndExit {
            get {
                return ResourceManager.GetString("CancelAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населений пункт.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Країна народження.
        /// </summary>
        public static string CountryOfBirth {
            get {
                return ResourceManager.GetString("CountryOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть тип адресу.
        /// </summary>
        public static string EnterAddressType {
            get {
                return ResourceManager.GetString("EnterAddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву міста.
        /// </summary>
        public static string EnterCityName {
            get {
                return ResourceManager.GetString("EnterCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву країни.
        /// </summary>
        public static string EnterCountryName {
            get {
                return ResourceManager.GetString("EnterCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву району.
        /// </summary>
        public static string EnterDistrictName {
            get {
                return ResourceManager.GetString("EnterDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть e-mail.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть фамілію.
        /// </summary>
        public static string EnterFamilyName {
            get {
                return ResourceManager.GetString("EnterFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ім&apos;я.
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть номер.
        /// </summary>
        public static string EnterNumber {
            get {
                return ResourceManager.GetString("EnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву області.
        /// </summary>
        public static string EnterRegionName {
            get {
                return ResourceManager.GetString("EnterRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ким приходиться.
        /// </summary>
        public static string EnterRelation {
            get {
                return ResourceManager.GetString("EnterRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву вулиці.
        /// </summary>
        public static string EnterStreetName {
            get {
                return ResourceManager.GetString("EnterStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамілія.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стать.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опекуни.
        /// </summary>
        public static string Guardians {
            get {
                return ResourceManager.GetString("Guardians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медична Інформаційна Система.
        /// </summary>
        public static string MedicalInformationSystem {
            get {
                return ResourceManager.GetString("MedicalInformationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий пацієнт.
        /// </summary>
        public static string NewPatient {
            get {
                return ResourceManager.GetString("NewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пацієнт.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пацієнти.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По-батькові.
        /// </summary>
        public static string Patronimic {
            get {
                return ResourceManager.GetString("Patronimic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефони.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місце народження.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ким приходиться.
        /// </summary>
        public static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти зміни та вийти.
        /// </summary>
        public static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть населений пункт.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть тип.
        /// </summary>
        public static string SelectCityType {
            get {
                return ResourceManager.GetString("SelectCityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть країну.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть район.
        /// </summary>
        public static string SelectDistrict {
            get {
                return ResourceManager.GetString("SelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть стать.
        /// </summary>
        public static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть область.
        /// </summary>
        public static string SelectRegion {
            get {
                return ResourceManager.GetString("SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть вулицю.
        /// </summary>
        public static string SelectStreet {
            get {
                return ResourceManager.GetString("SelectStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть тип вулиці.
        /// </summary>
        public static string SelectStreetType {
            get {
                return ResourceManager.GetString("SelectStreetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть тип.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вулиця.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ідентифікаційний код.
        /// </summary>
        public static string TaxId {
            get {
                return ResourceManager.GetString("TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підопічні.
        /// </summary>
        public static string Wards {
            get {
                return ResourceManager.GetString("Wards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік народження.
        /// </summary>
        public static string YearOfBirth {
            get {
                return ResourceManager.GetString("YearOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Індекс.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
